services:
  server:
    image: qmcgaw/gluetun:v3.41.3@sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
      - "8000:8000"
    volumes:
      - ${APP_DATA_DIR}/data:/gluetun
    environment:
      # CyberGhost VPN Configuration
      - VPN_SERVICE_PROVIDER=cyberghost
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${CYBERGHOST_USERNAME}
      - OPENVPN_PASSWORD=${CYBERGHOST_PASSWORD}
      - OPENVPN_CERT=${OPENVPN_CERT}
      - OPENVPN_KEY=${OPENVPN_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      # Enable Control server
      - HTTP_CONTROL_SERVER_ADDRESS=:8000  # 👈 fixed: = not :
      - HTTP_CONTROL_SERVER_LOG=on
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    stop_grace_period: 1m