services:
  app_proxy:
    environment:
      APP_HOST: maxibor-gluetun_server_1
      APP_PORT: 8989
      PROXY_AUTH_WHITELIST: /api/*
      PROXY_AUTH_ADD: 'false'

  server:
    image: linuxserver/sonarr:4.0.16@sha256:4b8a853b76337cd5de5f69961e23b7d0792ce7bf0a8be083dd7202ef670bfc34
    network_mode: "container:maxibor-gluetun_server_1"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads/complete:/downloads
      - ${UMBREL_ROOT}/home/Downloads/shows:/shows
    restart: unless-stopped
    stop_grace_period: 1m