services:
  app_proxy:
    environment:
      APP_HOST: maxibor-gluetun_server_1
      APP_PORT: 8989
      PROXY_AUTH_WHITELIST: /api/*
      PROXY_AUTH_ADD: 'false'

  server:
    image: linuxserver/sonarr:4.0.19@sha256:4b025354d338999e03bf6dbdadcdde94815d39d4a5aba5de3cdc86a56d7d6c51
    network_mode: "container:maxibor-gluetun_server_1"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads/complete:/downloads
      - ${UMBREL_ROOT}/home/Downloads/shows:/shows
    restart: unless-stopped
    stop_grace_period: 1m