services:
  app_proxy:
    environment:
      APP_HOST: maxibor-gluetun_server_1
      APP_PORT: 8090
      PROXY_AUTH_WHITELIST: "*"
      PROXY_AUTH_ADD: 'false'

  server:
    image: lscr.io/linuxserver/qbittorrent:5.2.3_v2.0.14-ls473@sha256:304b19cf94bf4fda534e0b086cab9c5f1a9e139a8180c05c0ad7d2ba1526fa99
    network_mode: "container:maxibor-gluetun_server_1"
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Downloads/complete:/downloads
      - ${UMBREL_ROOT}/home/Downloads/incomplete:/incomplete
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8090
    mem_limit: 2g
    restart: unless-stopped
    stop_grace_period: 1m